/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file    main.h
  * @brief   Header for main.c (auto-generated by STM32CubeMX, augmented).
  ******************************************************************************
  */
/* USER CODE END Header */

#ifndef __MAIN_H
#define __MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include "stm32l4xx_hal.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
/* USER CODE END Includes */

/* Exported types ------------------------------------------------------------*/
/* USER CODE BEGIN ET */
/* USER CODE END ET */

/* Exported constants --------------------------------------------------------*/
/* USER CODE BEGIN EC */
/* USER CODE END EC */

/* Exported macro ------------------------------------------------------------*/
/* USER CODE BEGIN EM */
/* USER CODE END EM */

/* Exported functions prototypes ---------------------------------------------*/
void Error_Handler(void);

/* USER CODE BEGIN EFP */
/* USER CODE END EFP */

/* Pin labels — match the GPIO_Label fields in motor_test_rig.ioc. */
#define USER_BTN_Pin    GPIO_PIN_0
#define USER_BTN_GPIO_Port  GPIOA
#define DSHOT_CH1_Pin   GPIO_PIN_8
#define DSHOT_CH1_GPIO_Port GPIOA
#define DSHOT_CH2_Pin   GPIO_PIN_9
#define DSHOT_CH2_GPIO_Port GPIOA
#define DSHOT_CH3_Pin   GPIO_PIN_10
#define DSHOT_CH3_GPIO_Port GPIOA
#define DSHOT_CH4_Pin   GPIO_PIN_11
#define DSHOT_CH4_GPIO_Port GPIOA
#define LD3_Pin         GPIO_PIN_3
#define LD3_GPIO_Port   GPIOB

/* USER CODE BEGIN Private defines */
/* USER CODE END Private defines */

#ifdef __cplusplus
}
#endif

#endif /* __MAIN_H */
